### ISSUE TITLE
Backend - Create function to determine if the describtion of the issue is detailed enough to generate a valid solution to it

### ISSUE THREAD

**Issue by Jlisowskyy** [kryczkal/AiBuy#8]
- [x] Test various prompts and techniques and validate some results (Possibly prepare some tests)
- [x] #43
- [x] Prepare some basic scenarios to test the prompt

**Comment by KwiatkowskiML** [comment]
added get_detailed_questions

**Comment by KwiatkowskiML** [comment]
added update_issue_details
